name: Ask Model

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to Model'
        required   : true
        type       : string
      model:
        description: 'Model to use'
        required   : false
        default    : 'gpt-4o'
        type       : choice
        options:
          - gpt-4o
          - gpt-4o-mini
          - gpt-4
          - gpt-3.5-turbo
          - gpt-5
          - gpt-5-nano
          - gpt-5-mini
          - gpt-5-chat
          - gpt-4-1
          - gpt-4-1-mini
          - gpt-4-1-nano
          - o3
          - o4-mini
          - DeepSeek-R1-0528
          - MAI-DS-R1
          - Grok-3
          - Grok-3-Mini
          - Phi-4-reasoning
          - Phi-4-mini-reasoning
          - Phi-4-multimodal-instruct
          - Llama-4-Scout-17B-16E-Instruct
          - Llama-4-Maverick-17B-128E-Instruct-FP8
          - Mistral-Medium-3-2505
          - Cohere-Command-A

jobs:
  ask_model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send message to Model
      env:
        PAT_TOKEN   : ${{ secrets.PAT_TOKEN }}
        GITHUB_MODEL: ${{ inputs.model }}
      run: |
        python -m workflows.github_models_chat "${{ inputs.message }}"
