name: GitHub Models Chat Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to send to GitHub Models'
        required   : true
        type       : string
      model:
        description: 'AI Model to use'
        required   : false
        default    : 'gpt-4o'
        type       : choice
        options:
          - gpt-4o
          - gpt-4o-mini
          - gpt-4
          - gpt-3.5-turbo

jobs:
  ask_model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send message to GitHub Models
      env:
        PAT_TOKEN   : ${{ secrets.PAT_TOKEN }}
        GITHUB_MODEL: ${{ inputs.model }}
      run: |
        python -m workflows.github_models_chat "${{ inputs.message }}"
